modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="kibounohana"
version="1.20.1-1.0.0"
# logoFile="logo.png" #optional
displayName="Corpse: Kibou no Hana"
authors="Rinko1231"
description='''
Die just like Orga Itsuka!
'''